---
version: 3

images:
  base_image:
    name: >-
      registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.18.19
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.19
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: hdefazio-mcp_fetch-1.1.0.tar.gz
    dest: configs

additional_build_steps:
  append_final: |
    RUN ansible-playbook ansible.mcp_builder.install_mcp \
        -e mcp_servers=github_mcp \
        -e github_mcp_build_repo_branch=v1.11.0
    RUN ansible-playbook hdefazio.mcp_fetch.install_fetch_mcp
